### ISSUE TITLE
Add section about when to use / when not to use this package to README

### ISSUE THREAD

**Issue by maelle** [cynkra/lazytest#2]

**Comment by maelle** [comment]
I wonder whether it's all that needed in the end.
This package does not provide the complicated+fragile tracing that was discussed in the testthat issue.
And since all tests are re-run once the initially failing ones are fixed, it's rather ok?

So, if there were a warning, what would it be?

**Comment by krlmlr** [comment]
THIS SOFTWARE IS PROVIDED AS IS 🤣 

I think it's fine the way it is.

**Comment by maelle** [comment]
Now I want to add this warning to cynkratemplate footer :joy_cat:
