### ISSUE TITLE
what are the auto-update commits

### ISSUE THREAD

**Issue by maelle** [cynkra/lazytest#25]
Like https://github.com/cynkra/lazytest/commit/2da562d69b56581ee9209b83aeda204e69e71363

**Comment by krlmlr** [comment]
Running `devtools::document()` and such.

**Comment by maelle** [comment]
In this case, because of the randomness of testthat emoji output, the commits often are "useless".

**Comment by krlmlr** [comment]
Should we fix the random seed?
